import { App, requestUrl, Notice } from 'obsidian';
import * as Y from 'yjs';
import { reconcileYText } from './reconcile';
import { getApiUrl } from './utils';

export interface FileManifest {
  [filePath: string]: {
    size: number;
    mtime: number;
    device?: string;
  };
}

function deepMerge(target: any, source: any): any {
  if (typeof target !== 'object' || target === null || typeof source !== 'object' || source === null) {
    return source !== undefined ? source : target;
  }
  if (Array.isArray(target) || Array.isArray(source)) {
    return source;
  }
  const merged = { ...target };
  for (const key of Object.keys(source)) {
    if (source[key] instanceof Object && key in target) {
      merged[key] = deepMerge(target[key], source[key]);
    } else {
      merged[key] = source[key];
    }
  }
  return merged;
}

/**
 * Filter mechanism to ignore temporary, transient, or large system files that
 * cause conflict spam or should not be synced.
 */
function shouldIgnore(path: string): boolean {
  const normalized = path.replace(/\\/g, '/');

  // Ephemeral/System directories
  if (
    normalized.startsWith('.git/') || normalized === '.git' ||
    normalized.startsWith('.trash/') || normalized === '.trash' ||
    normalized.startsWith('node_modules/') || normalized === 'node_modules' ||
    normalized.startsWith('Sync Conflicts/') || normalized === 'Sync Conflicts'
  ) {
    return true;
  }

  // The plugin's own folder must never sync between devices:
  // data.json, main.js, server.bundle.js, manifest.json would clobber each other.
  if (normalized.includes('.obsidian/plugins/live-cursor')) {
    return true;
  }

  // Conflict copy files (generated by previous sync versions)
  if (normalized.includes('(Conflict from ')) {
    return true;
  }

  // Specific noise files and device-specific workspace configurations
  if (
    normalized.includes('.obsidian/workspace') || // covers workspace.json, workspace-mobile.json, workspaces.json, etc.
    normalized.endsWith('/.DS_Store') || normalized === '.DS_Store' ||
    normalized.endsWith('/thumbs.db') || normalized === 'thumbs.db'
  ) {
    return true;
  }

  return false;
}

export class ConfigSyncEngine {
  private static isSyncing = false;
  private pendingDeletions: Set<string> = new Set();
  private persistPendingDeletions: () => void;

  constructor(
    private app: App,
    public serverUrl: string,
    private user: string,
    private pass: string,
    public workspace: string = 'default-workspace',
    private deviceName: string = 'Unknown Device',
    persistPendingDeletions?: () => void
  ) {
    this.persistPendingDeletions = persistPendingDeletions || (() => {});
  }

  public loadPendingDeletions(paths: string[]) {
    this.pendingDeletions = new Set(paths.filter(Boolean));
  }

  public getPendingDeletionPaths(): string[] {
    return [...this.pendingDeletions];
  }

  private authHeaders(): Record<string, string> {
    return { Authorization: `Bearer ${this.pass}` };
  }

  private async getRemoteManifest(): Promise<FileManifest> {
    const url = `${getApiUrl(this.serverUrl, '/manifest')}?workspace=${encodeURIComponent(this.workspace)}`;
    const res = await requestUrl({ url, method: 'GET', headers: this.authHeaders() });
    if (res.status !== 200) throw new Error(`Server returned HTTP ${res.status}: ${res.text || 'No response body'}`);
    return res.json as FileManifest;
  }

  private async uploadFile(relativePath: string, data: ArrayBuffer, mtime: number) {
    const url = `${getApiUrl(this.serverUrl, '/upload')}?workspace=${encodeURIComponent(this.workspace)}&path=${encodeURIComponent(relativePath)}&mtime=${mtime}`;
    const res = await requestUrl({
      url,
      method: 'POST',
      body: data,
      headers: this.authHeaders(),
    });
    if (res.status !== 200) throw new Error(`Upload failed: ${res.text}`);
  }

  private async downloadFile(relativePath: string): Promise<ArrayBuffer> {
    const url = `${getApiUrl(this.serverUrl, '/download')}?workspace=${encodeURIComponent(this.workspace)}&path=${encodeURIComponent(relativePath)}`;
    const res = await requestUrl({ url, method: 'GET', headers: this.authHeaders() });
    if (res.status !== 200) throw new Error('Download failed');
    return res.arrayBuffer;
  }

  /**
   * Registers a file for remote deletion. Deletions are retried on every sync
   * until the server confirms, so files deleted while offline are not resurrected.
   */
  public async enqueueDeletion(relativePath: string) {
    if (shouldIgnore(relativePath)) return;
    this.pendingDeletions.add(relativePath);
    this.persistPendingDeletions();
    await this.flushPendingDeletions();
  }

  private async flushPendingDeletions(): Promise<void> {
    if (this.pendingDeletions.size === 0) return;

    for (const relPath of [...this.pendingDeletions]) {
      try {
        const url = `${getApiUrl(this.serverUrl, '/delete')}?workspace=${encodeURIComponent(this.workspace)}&path=${encodeURIComponent(relPath)}`;
        const res = await requestUrl({ url, method: 'DELETE', headers: this.authHeaders() });
        if (res.status === 200 || res.status === 404) {
          this.pendingDeletions.delete(relPath);
        }
      } catch (e) {
        console.warn(`[LiveCursor] Failed to delete remote file ${relPath} (will retry):`, e);
      }
    }
    this.persistPendingDeletions();
  }

  /**
   * Purges the server's room-state database for the current workspace only.
   */
  public async reconstructDatabase(): Promise<void> {
    const url = `${getApiUrl(this.serverUrl, '/reconstruct-db')}?workspace=${encodeURIComponent(this.workspace)}`;
    const res = await requestUrl({ url, method: 'POST', headers: this.authHeaders() });
    if (res.status !== 200) {
      throw new Error(`Server returned HTTP ${res.status}: ${res.text || 'No response body'}`);
    }
  }

  /**
   * Writes binary data directly to the Obsidian vault using low-level adapter APIs
   * to bypass standard hidden-file limitations of app.vault.
   */
  private async writeToVaultUI(relPath: string, data: ArrayBuffer) {
    await this.app.vault.adapter.writeBinary(relPath, data);
  }

  private getConflictPath(path: string, deviceName: string): string {
    const normalized = path.replace(/\\/g, '/');
    const idx = normalized.lastIndexOf('.');
    if (idx !== -1 && idx > normalized.lastIndexOf('/')) {
      return normalized.substring(0, idx) + ` (Conflict from ${deviceName})` + normalized.substring(idx);
    }
    return normalized + ` (Conflict from ${deviceName})`;
  }

  /**
   * Ensures parent directories exist recursively using the raw file system adapter.
   */
  private async ensureDirExists(relPath: string, configDir: string) {
    const normalized = relPath.replace(/\\/g, '/');
    const parts = normalized.split('/');
    let cur = configDir;
    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i] as string;
      cur = cur ? cur + '/' + part : part;
      const exists = await this.app.vault.adapter.exists(cur);
      if (!exists) {
        await this.app.vault.adapter.mkdir(cur).catch(() => {});
      }
    }
  }

  /**
   * Performs an incremental whole-vault configuration and file sync.
   * Compares the local file system manifest with the server manifest, pushing and pulling
   * updates as needed, and resolving conflicts automatically.
   */
  public async syncConfig(silent: boolean = false) {
    if (ConfigSyncEngine.isSyncing) {
      if (!silent) new Notice('Sync already in progress...');
      return;
    }
    ConfigSyncEngine.isSyncing = true;
    if (!silent) new Notice('Syncing vault files...', 2000);

    try {
      // Retry any deletions that failed while the server was unreachable
      await this.flushPendingDeletions();

      const remoteManifest = await this.getRemoteManifest();
      const localFiles: { path: string, stat: any }[] = [];

      // Recursive local scan starting from the vault root ""
      const scanDir = async (dir: string) => {
        if (shouldIgnore(dir)) return;

        const list = await this.app.vault.adapter.list(dir);
        for (const file of list.files) {
          if (shouldIgnore(file)) continue;
          const stat = await this.app.vault.adapter.stat(file);
          if (stat) localFiles.push({ path: file, stat });
        }
        for (const folder of list.folders) {
          await scanDir(folder);
        }
      };

      await scanDir("");

      // Map local files by relative path for unified syncing
      const localMap = new Map<string, { path: string, stat: any }>();
      for (const local of localFiles) {
        const relPath = local.path.replace(/\\/g, '/');
        localMap.set(relPath, local);
      }

      // Collect all unique relative paths across local and remote
      const allPaths = new Set<string>([
        ...localMap.keys(),
        ...Object.keys(remoteManifest)
      ]);

      let actionsCount = 0;

      for (const relPath of allPaths) {
        const local = localMap.get(relPath);
        const remote = remoteManifest[relPath];

        if (local && !remote) {
          // File exists only locally -> Upload
          const data = await this.app.vault.adapter.readBinary(local.path);
          await this.uploadFile(relPath, data, local.stat.mtime);
          actionsCount++;
        } else if (!local && remote) {
          if (this.pendingDeletions.has(relPath)) {
            // We deleted this file locally but the server delete hasn't confirmed yet;
            // don't pull it back down. Retry the deletion instead.
            await this.flushPendingDeletions();
            continue;
          }
          // File exists only remotely -> Download
          await this.ensureDirExists(relPath, '');
          const data = await this.downloadFile(relPath);
          await this.writeToVaultUI(relPath, data);
          actionsCount++;
        } else if (local && remote) {
          // File exists in both -> Check for modification differences
          const timeDiff = Math.abs(local.stat.mtime - remote.mtime);

          if (timeDiff > 2000) {
            // Contents or timestamps differ. Let's read both.
            const localData = await this.app.vault.adapter.readBinary(local.path);
            const remoteData = await this.downloadFile(relPath);

            // Compare binary content quickly
            const localBytes = new Uint8Array(localData);
            const remoteBytes = new Uint8Array(remoteData);
            let contentsMatch = localBytes.length === remoteBytes.length;
            if (contentsMatch) {
              for (let i = 0; i < localBytes.length; i++) {
                if (localBytes[i] !== remoteBytes[i]) {
                  contentsMatch = false;
                  break;
                }
              }
            }

            if (contentsMatch) {
              // Contents match exactly; just align the timestamps to the newest modified time
              if (local.stat.mtime > remote.mtime) {
                await this.uploadFile(relPath, localData, local.stat.mtime);
              } else {
                await this.writeToVaultUI(relPath, remoteData);
              }
            } else {
              // Conflict: Contents are different and timestamps differ.
              if (relPath.endsWith('.md')) {
                // Automatic CRDT note merge
                try {
                  console.log(`[LiveCursor] Automatically merging CRDT conflict for note: ${relPath}`);

                  // 1. Fetch the server's Yjs room state binary update
                  const urlGet = `${getApiUrl(this.serverUrl, '/room-state')}?workspace=${encodeURIComponent(this.workspace)}&path=${encodeURIComponent(relPath)}`;
                  const resGet = await requestUrl({ url: urlGet, method: 'GET', headers: this.authHeaders() });

                  const doc = new Y.Doc();
                  if (resGet.status === 200 && resGet.arrayBuffer.byteLength > 0) {
                    Y.applyUpdate(doc, new Uint8Array(resGet.arrayBuffer));
                  }

                  // 2. Read the local disk file content
                  const decoder = new TextDecoder('utf-8');
                  const localText = decoder.decode(new Uint8Array(localData));

                  // 3. Reconcile the Yjs document with our local offline edits
                  const ytext = doc.getText('content');

                  // If the Yjs doc was empty, initialize it with the remote content first
                  if (ytext.toString() === '') {
                    const remoteText = decoder.decode(new Uint8Array(remoteData));
                    ytext.insert(0, remoteText);
                  }

                  // Reconcile with local text to merge offline edits cleanly
                  reconcileYText(ytext, localText);

                  // 4. Encode the merged state as a Yjs update
                  const mergedUpdate = Y.encodeStateAsUpdate(doc);

                  // 5. Send the merged update back to the server
                  const urlPost = `${getApiUrl(this.serverUrl, '/room-state')}?workspace=${encodeURIComponent(this.workspace)}&path=${encodeURIComponent(relPath)}`;
                  const resPost = await requestUrl({
                    url: urlPost,
                    method: 'POST',
                    body: mergedUpdate.buffer as ArrayBuffer,
                    headers: this.authHeaders(),
                  });

                  if (resPost.status !== 200) throw new Error(`CRDT Merge POST failed: ${resPost.text}`);

                  // 6. Write the merged text back to our local disk file
                  const mergedText = ytext.toString();
                  const encoder = new TextEncoder();
                  await this.writeToVaultUI(relPath, encoder.encode(mergedText).buffer as ArrayBuffer);

                  actionsCount++;
                  console.log(`[LiveCursor] CRDT merge successful for note: ${relPath}`);
                } catch (crdtErr) {
                  console.error(`[LiveCursor] CRDT merge failed for ${relPath}, falling back to silent mtime resolution:`, crdtErr);
                  // Fallback: Silent latest modified wins (Zero Conflicts Protocol!)
                  if (local.stat.mtime > remote.mtime) {
                    await this.uploadFile(relPath, localData, local.stat.mtime);
                  } else {
                    await this.writeToVaultUI(relPath, remoteData);
                  }
                  actionsCount++;
                }
              } else if (relPath.endsWith('.json')) {
                // Automatic JSON merge
                try {
                  const decoder = new TextDecoder('utf-8');
                  const encoder = new TextEncoder();

                  const localJson = JSON.parse(decoder.decode(localBytes));
                  const remoteJson = JSON.parse(decoder.decode(remoteBytes));

                  const mergedJson = deepMerge(localJson, remoteJson);
                  const mergedData = encoder.encode(JSON.stringify(mergedJson, null, 2)).buffer;

                  const mergedMtime = Math.max(local.stat.mtime, remote.mtime);

                  // Save merged file locally and upload to remote
                  await this.writeToVaultUI(relPath, mergedData);
                  await this.uploadFile(relPath, mergedData, mergedMtime);
                  actionsCount++;
                  console.log(`[LiveCursor] Automatically merged JSON conflict for config file: ${relPath}`);
                } catch (jsonErr) {
                  console.warn(`[LiveCursor] JSON merge failed for ${relPath}, falling back to silent mtime resolution:`, jsonErr);
                  // Fallback: Silent latest modified wins (Zero Conflicts Protocol!)
                  if (local.stat.mtime > remote.mtime) {
                    await this.uploadFile(relPath, localData, local.stat.mtime);
                  } else {
                    await this.writeToVaultUI(relPath, remoteData);
                  }
                  actionsCount++;
                }
              } else {
                // Non-JSON/Non-Markdown binary files: Resolve silently via latest modification time (mtime)
                console.log(`[LiveCursor] Silently resolving binary conflict for ${relPath} via latest mtime`);
                if (local.stat.mtime > remote.mtime) {
                  await this.uploadFile(relPath, localData, local.stat.mtime);
                } else {
                  await this.writeToVaultUI(relPath, remoteData);
                }
                actionsCount++;
              }
            }
          }
        }
      }

      if (!silent) new Notice(actionsCount > 0 ? `Sync complete (${actionsCount} updated)` : 'Vault in sync.', 2000);
    } catch (e: any) {
      console.error('[LiveCursor] Sync Error:', e);
      if (!silent) {
        const errMsg = e.message || String(e);
        new Notice(`Sync failed: ${errMsg}`, 5000);
      }
    } finally {
      ConfigSyncEngine.isSyncing = false;
    }
  }
}
