import esbuild from "esbuild";
import process from "process";
import { builtinModules, createRequire } from "module";

const require = createRequire(import.meta.url);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Self-contained bundle of the sync server (ws + yjs + y-websocket) so the
// plugin can spawn it from a vault's plugin folder without any node_modules.
const buildServerBundle = async () => {
	await esbuild.build({
		banner: {
			js: banner,
		},
		entryPoints: ["server.js"],
		bundle: true,
		platform: "node",
		format: "cjs",
		target: "node20",
		logLevel: "info",
		outfile: "server.bundle.js",
	});
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"child_process",
		"fs",
		"path",
		"os",
		"crypto",
		"net",
		"tls",
		"http",
		"https",
		"zlib",
		"url"
	],
	alias: {
		"process": "process",
		"buffer": "buffer",
		"events": "events",
		"stream": "stream-browserify",
		"util": "util"
	},
	inject: ["./process-shim.js"],
	define: {
		"process.env.NODE_ENV": '"production"',
		"global": "window"
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	await buildServerBundle();
	process.exit(0);
} else {
	await context.watch();
}
